-- OpenEV Data SQLite Schema
-- Reference schema for SQLite database output
-- Generated by ev-etl

-- Main vehicles table with denormalized key attributes
CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    unique_code TEXT UNIQUE NOT NULL,
    
    -- Identification
    make_slug TEXT NOT NULL,
    make_name TEXT NOT NULL,
    model_slug TEXT NOT NULL,
    model_name TEXT NOT NULL,
    year INTEGER NOT NULL,
    trim_slug TEXT NOT NULL,
    trim_name TEXT NOT NULL,
    variant_slug TEXT,
    variant_name TEXT,
    
    -- Classification
    vehicle_type TEXT NOT NULL,
    
    -- Powertrain
    drivetrain TEXT NOT NULL,
    system_power_kw REAL,
    system_torque_nm REAL,
    
    -- Battery
    battery_capacity_gross_kwh REAL,
    battery_capacity_net_kwh REAL,
    battery_chemistry TEXT,
    
    -- Charging
    dc_max_power_kw REAL,
    ac_max_power_kw REAL,
    
    -- Range
    range_wltp_km REAL,
    range_epa_km REAL,
    
    -- Performance
    acceleration_0_100_s REAL,
    top_speed_kmh REAL,
    
    -- Full JSON data
    json_data TEXT NOT NULL,
    
    -- Metadata
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Charge ports (normalized)
CREATE TABLE IF NOT EXISTS charge_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vehicle_id INTEGER NOT NULL,
    kind TEXT NOT NULL,
    connector TEXT NOT NULL,
    location_side TEXT,
    location_position TEXT,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

-- Range ratings (normalized)
CREATE TABLE IF NOT EXISTS range_ratings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vehicle_id INTEGER NOT NULL,
    cycle TEXT NOT NULL,
    range_km REAL NOT NULL,
    notes TEXT,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

-- Data sources (normalized)
CREATE TABLE IF NOT EXISTS sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vehicle_id INTEGER NOT NULL,
    source_type TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    accessed_at TEXT NOT NULL,
    publisher TEXT,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_vehicles_make ON vehicles(make_slug);
CREATE INDEX IF NOT EXISTS idx_vehicles_model ON vehicles(model_slug);
CREATE INDEX IF NOT EXISTS idx_vehicles_year ON vehicles(year);
CREATE INDEX IF NOT EXISTS idx_vehicles_composite ON vehicles(make_slug, model_slug, year, trim_slug);
CREATE INDEX IF NOT EXISTS idx_vehicles_type ON vehicles(vehicle_type);
CREATE INDEX IF NOT EXISTS idx_vehicles_unique_code ON vehicles(unique_code);

CREATE INDEX IF NOT EXISTS idx_charge_ports_vehicle ON charge_ports(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_range_ratings_vehicle ON range_ratings(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_sources_vehicle ON sources(vehicle_id);

-- Full-text search (SQLite FTS5)
-- CREATE VIRTUAL TABLE IF NOT EXISTS vehicles_fts USING fts5(
--     make_name,
--     model_name,
--     trim_name,
--     content=vehicles,
--     content_rowid=id
-- );
